version: '3.9'
services:
  laravel-php:
    build:
      context: ./
      args:
        APP_ENV: ${APP_ENV}
    container_name: laravel-php
    volumes:
      - ./:/var/www
    networks:
      - laravel-basic
  laravel-nginx:
    image: nginx:1.25
    container_name: laravel-nginx
    ports:
      - 8000:80
    volumes:
      - ./public:/var/www/html
      - ./build/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-basic
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
      - 9411:9411 # zipkin reciver
  promtail:
    image: grafana/promtail:latest
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml
      - ./storage/logs:/var/log
    command: -config.file=/etc/promtail/config.yml
  prometheus:
    image: prom/prometheus:v2.45.0
    command:
      - --web.enable-remote-write-receiver
      - --enable-feature=native-histograms
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

networks:
  laravel-basic:
    driver: bridge
