version: '3.9'
services:
  laravel-php:
    build: 
      context: ./
      args:
        APP_ENV: ${APP_ENV}
    container_name: laravel-php
    volumes:
      - ./:/var/www
    networks:
      - laravel-basic
  laravel-nginx:
    image: nginx:1.25
    container_name: laravel-nginx
    ports:
      - 8000:80
    volumes:
      - ./public:/var/www/html
      - ./build/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-basic
networks:
  laravel-basic:
    driver: bridge